### PR TITLE
deprecation message

### PR DESCRIPTION
**Pull request by jcarres-mdsol**
Pointing users to the right gem

@jamescway  @adriancole

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
Thanks for doing this.. I'd move the deprecated to the top of the file and separate the rest with a line?

**Comment by jcarres-mdsol** [comment]
@adriancole  done

**Comment by codefromthecrypt** [comment]
sorry for the nit.. instead of adding blank lines, maybe make a horizontal line like this?
`* * *`
renders like this:

---

**Comment by jcarres-mdsol** [comment]
The three **\* together in line 9 should be rendering that line also

**Comment by codefromthecrypt** [comment]
ps should we rename the repo to `deprecated-faraday-zipkin`?

**Comment by jcarres-mdsol** [comment]
Renaming the repo would break Gemfiles which are referencing Github directly. Sure then they will very much notice stuff have been deprecated :laughing:

**Comment by codefromthecrypt** [comment]
ok maybe rename after we have a release or two :)

**Pull request merged**
